In [37]:
import pandas as pd
from sqlalchemy import create_engine, types
from sqlalchemy import text # to be able to pass string

In [38]:
pwd

'c:\\Users\\srnwn\\Documents\\neueFische\\Capstone\\scripts'

In [39]:
demo = pd.read_csv("../data/NHANES_2017-2018/demographics2017.csv")
diet = pd.read_csv("../data/NHANES_2017-2018/dietary2017.csv")
lab = pd.read_csv("../data/NHANES_2017-2018/laboratory2017.csv")
exam = pd.read_csv("../data/NHANES_2017-2018/examination2017.csv")
quest = pd.read_csv("../data/NHANES_2017-2018/questionnaire2017.csv")

C:\Users\srnwn\AppData\Local\Temp\ipykernel_6984\3535719052.py:4: DtypeWarning: Columns (87,89) have mixed types. Specify dtype option on import or set low_memory=False.
  exam = pd.read_csv("../data/NHANES_2017-2018/examination2017.csv")
C:\Users\srnwn\AppData\Local\Temp\ipykernel_6984\3535719052.py:5: DtypeWarning: Columns (807,808,810,811,827,828) have mixed types. Specify dtype option on import or set low_memory=False.
  quest = pd.read_csv("../data/NHANES_2017-2018/questionnaire2017.csv")

In [40]:
## Demographics

demo_clean = demo.loc[:,[
    "SEQN",                 # ID
    "RIAGENDR",             # Gender
    "RIDAGEYR",             # Age
    "RIDRETH3",             # Ethnicity
    "DMDBORN4",             # Country of Birth
    "DMDCITZN",             # US-Citizenship
    "DMDEDUC2",             # Highschool Grad?
    "DMDEDUC3",             # College Degree?
    "DMDHHSIZ",             # Household Size
    "DMDHHSZA",             # No of Kids < 6 yr in Household?
    "DMDHHSZB",             # No of Kids between 6 and 17
    "INDFMIN2",             # Total family Income
    "RIDEXPRG"              # Pregnancy status
    ]]
demo_columns = {
    "SEQN" : "ID",
    "RIAGENDR": "gender",
    "RIDAGEYR": "age",
    "RIDRETH3": 'ethnicity',
    "DMDBORN4": "country_of_birth",
    "DMDCITZN": "us_citizen",
    "DMDEDUC2": "education_adult",
    "DMDEDUC3": "education_adolescent",
    "DMDHHSIZ": "household_size",
    "DMDHHSZA": "no_of_kids_u6",
    "DMDHHSZB": "no_of_kids_btw_6_17",
    "INDFMIN2": "total_income",
    "RIDEXPRG": "pregnancy_status"
    }

## Diet

diet_clean = diet.loc[:,[
    'SEQN',                 # ID
    'DR1TKCAL',             # Total Calories
    'DR1TPROT',             # Total Protein
    'DR1TCARB',             # Total Carbohydrates
    'DR1TSUGR',             # Total Sugar
    'DR1_320Z',             # Total Water drank
    'DR1TTFAT',             # Total Fat
    'DR1TMFAT',             # MUFA
    'DR1TPFAT',             # PUFA
    'DR1TCHOL',             # Cholesterin
    'DR1TFIBE',             # Total Fiber
    'DR1TALCO',             # Total Alcohol
    'DR1TVARA',             # Vit A
    'DR1TVB1',              # Vit B1 (Thiamin)
    'DR1TVB2',              # Vit B2 (Riboflavin)
    'DR1TNIAC',             # Vit B3 (Niacin)
    'DR1TVB6',              # Vit B6 (Pyridoxin)
    'DR1TFA',               # Vit B9 (Folic Acid)
    'DR1TVB12',             # Vit B12 (Cobalamin)
    'DR1TVC',               # Vit C
    'DR1TVD',               # Vit D
    'DR1TATOC',             # Vit E
    'DR1TCALC',             # Calcium
    'DR1TIRON',             # Iron
    'DR1TZINC',             # Zinc
    'DR1TSODI',             # Sodium
    'DR1TPOTA',             # Potassium
    'DR1TCAFF'              # Caffeine
    ]]

diet_columns = {
    'SEQN': 'ID',
    'DR1TKCAL': 'daily_calories',
    'DR1TPROT': 'total_protein',
    'DR1TCARB': 'total_carbohydrates',
    'DR1TSUGR': 'total_sugar',
    'DR1_320Z': 'total_water',
    'DR1TTFAT': 'total_fat',
    'DR1TMFAT': 'mufa',
    'DR1TPFAT': 'pufa',
    'DR1TCHOL': 'cholesterin_diet',
    'DR1TFIBE': 'total_fiber',
    'DR1TALCO': 'total_alcohol',
    'DR1TVARA': 'vit_a',
    'DR1TVB1': 'vit_b1',
    'DR1TVB2': 'vit_b2',
    'DR1TNIAC': 'vit_b3',
    'DR1TVB6': 'vit_b6',
    'DR1TFA': 'vit_b9',
    'DR1TVB12': 'vit_b12',
    'DR1TVC': 'vit_c',
    'DR1TVD': 'vit_d_diet',
    'DR1TATOC': 'vit_e',
    'DR1TCALC': 'calcium',
    'DR1TIRON': 'iron',
    'DR1TZINC': 'zinc',
    'DR1TSODI': 'sodium',
    'DR1TPOTA': 'potassium',
    'DR1TCAFF': 'caffeine'
}

## Exam

exam_clean = exam.loc[:,[
    'SEQN',                 # ID
    'BMXWT',                # Weight
    'BMXHT',                # Height
    'BMXBMI',               # BMI
    'BMXWAIST',             # Waist circumference
    'BPXSY1',               # Systolic BP
    'BPXDI1',               # Diastolic BP
    'BPXPULS',              # Pulse
    'BPXPLS'                # Pulse / 60
    ]]

exam_columns = {
    'SEQN': 'ID',
    'BMXWT': 'weight',
    'BMXHT': 'height',
    'BMXBMI': 'bmi',
    'BMXWAIST': 'waist_circumference',
    'BPXSY1': 'systolic_bp',
    'BPXDI1': 'diastolic_bp',
    'BPXPULS': 'pulse',
    'BPXPLS': 'Pulse_60s'
}

## Questionnaire
quest_clean = quest.loc[:,[
    'SEQN',                 # ID
    'PAQ605',               # vigorous sport over last 7 days 
    'PAQ610',               # numbers of days with vigorous work
    'PAQ620',               # Work with physical activity?
    'PAQ635',               # avg min sports / week
    'PAQ640',               # Days on which you bike or walk more than 10 mins/week
    'PAQ650',               # vig reg activities
    'PAD660',               # vigorous Sport         
    'PAD675',               # Time spent doing physical activities / day
    'PAD680',               # Time spent sitting
    'MCQ010',               # Asthma?
    'MCQ080',               # Has a Doctor ever said: "you are overweight!" ?
    'MCQ220',               # Has a Doctor ever said: "You have cancer" ?
    'SMQ040',               # Do you smoke?
    'ALQ130',               # On avg how many drinks on days you drank alcohol?
    'SLQ050',               # Ever told a doctor: Trouble sleeping?           
    'DIQ010',               # Has a Doctor ever told you: "You have Diabetes"?
    'SMD650',               # avg_cig_p_day
    'BPQ050A',              # taking BP Medicine?
    # 'SLD010H'                # Hours of Sleep per Day
    'SLD012'
    ]]

quest_columns = {
    'SEQN': 'ID',
    'PAQ605': 'sport_vig_o_l_7_days',
    'PAQ610': 'Work_days_with_vig_activity',
    'PAQ620': 'physical_activity_work',
    'PAQ635': 'avg_min_walk/bic',
    'PAQ640': 'walk_<10_minutes_p_day',
    'PAQ650': 'muscle_str_training',
    'PAD660': 'sport_vig',
    'PAD675': 'sport_days',
    'PAD680': 'sitting_per_day',
    'ALQ130': 'alcoholic_drinks',
    'SMQ040': 'smoker',
    'MCQ010': 'asthma',
    'MCQ080': 'overweight',
    'MCQ220': 'cancer',
    'SLQ050': 'trouble_sleeping',
    'DIQ010': 'diabetes',
    'SMD650': 'cig_p_d',
    'BPQ050A': 'BP_med',
    # 'SLD010H': 'hours_sleeping'
    'SLD012': 'hours_sleeping'
}

## laboratory

lab_clean = lab.loc[:,[
    'SEQN',             # ID
    'LBXGLU',           # Glucose in Blood mg/dL
    'LBDINSI',          # Insulin pmol/L
    'LBXTC',            # Cholesterol mg/dL
    'LBXTR',            # Triglyceride mg/dL
    'LBDLDL',           # LDL-cholesterol mg/dL
    'LBXSAL',           # Albumin
    'LBXSATSI',         # Alanine Aminotransferase ALT U/L
    'LBXSGTSI',         # Gamma glutamyl transferase
    'LBXSAPSI',         # Alkaline phosphatase (IU/L)
    'LBXVIDMS',         # vitamin D2 + D3
    'URXUCR',           # Urinary creatinine (mg/dL)
    'URXUMA',           # Albumin, urine (ug/mL)
    'URDACT'            # Albumin creatinine ratio (mg/g)
]]

lab_columns = {
    'SEQN': 'ID',
    'LBXGLU': 'blood_glucose',
    'LBDINSI': 'insulin',
    'LBXTC': 'cholesterin_lab',
    'LBXTR': 'triaclyglycerole',
    'LBDLDL': 'ldl',
    'LBXSAL': 'albumin',
    'LBXSATSI': 'ALT',
    'LBXSGTSI': 'gamma_glutamyl_transferase',
    'LBXSAPSI': 'alkaline_phosphatase',
    'LBXVIDMS': 'vit_d_lab',
    'URXUCR': 'urinary_creatinine',
    'URXUMA': 'albumine',
    'URDACT': 'albumine_creatinine_ratio'
}

In [41]:
demo_clean.rename(columns=demo_columns, inplace = True)
diet_clean.rename(columns=diet_columns, inplace = True)
lab_clean.rename(columns=lab_columns, inplace = True)
exam_clean.rename(columns=exam_columns, inplace = True)
quest_clean.rename(columns=quest_columns, inplace = True)

In [42]:
data_merged = demo_clean.merge(diet_clean, how = 'inner', on='ID').merge(exam_clean, how='inner', on='ID').merge(lab_clean, how='inner', on='ID').merge(quest_clean, how='inner', on='ID')

In [43]:
int_list = [
    'ID',
    'age',
    'household_size',
    'no_of_kids_u6', 
    'no_of_kids_btw_6_17',
    'sitting_per_day',
    'sport_days',
    'walk_<10_minutes_p_day',
    'alcoholic_drinks']

data_merged[int_list] = data_merged[int_list].astype('Int64')

str_list = [
       'gender',
       'country_of_birth',
       'us_citizen',
       'ethnicity',
       'education_adult',
       'education_adolescent',
       'pregnancy_status',
       'physical_activity_work',
       'asthma',
       'overweight',
       'cancer',
       'smoker',
       'trouble_sleeping',
       'diabetes'#,
       #'hours_sleeping'
       ]

data_merged[str_list] = data_merged[str_list].astype('str')

In [44]:
# data_merged['hours_sleeping'] = data_merged['hours_sleeping'].map({
#     '2.0':'2',
#     '3.0':'3',
#     '4.0':'4',
#     '5.0':'5',
#     '6.0':'6',
#     '7.0':'7',
#     '8.0':'8',
#     '9.0':'9', 
#     '10.0':'10',
#     '11.0':'11',
#     '12.0':'12',
#     '77': 'unknown',
#     '99': 'unknown'
# }).fillna('unknown')

data_merged['gender'] = data_merged['gender'].map({
    '1.0': 'male',
    '2.0': 'female'
}).fillna('unknown')

data_merged['country_of_birth'] = data_merged['country_of_birth'].map({
    '1.0': 'USA',
    '2.0': 'others'
}).fillna('unknown')

data_merged['us_citizen'] = data_merged['us_citizen'].map({
    '1.0': 'US-citizen',
    '2.0': 'US-citizen',
    '7.0': 'not a citizen',
    '9.0': 'unknown'
}).fillna('unknown')

data_merged['pregnancy_status'] = data_merged['pregnancy_status'].map({
    '1.0': 'pregnant',
    '2.0': 'not pregnant',
    '3.0': 'unknown'
}).fillna('unknown')

data_merged['physical_activity_work'] = data_merged['physical_activity_work'].map({
    '1.0': 'yes',
    '2.0': 'no',
    '9.0': 'unknown',
    '7.0': 'unknown'
}).fillna('unknown')

data_merged['ethnicity'] = data_merged['ethnicity'].map({
    '1.0': 'mexican',
    '2.0': 'hispanic',
    '3.0': 'white',
    '4.0': 'black',
    '6.0': 'asian',
    '7.0': 'others'
}).fillna('unknown')

data_merged['smoker'] = data_merged['smoker'].map({
    '1.0': 'every day',
    '2.0': 'some days',
    '3.0': 'not at all',
    '9.0': 'unknown',
    '7.0': 'unknown'
}).fillna('unknown')

data_merged['overweight'] = data_merged['overweight'].map({
    '1.0': 'yes',
    '2.0': 'no',
    '3.0': 'refused',
    '9.0': 'unknown'
}).fillna('unknown')

data_merged['cancer'] = data_merged['cancer'].map({
    '1.0': 'yes',
    '2.0': 'no',
    '3.0': 'refused',
    '9.0': 'unknown'
}).fillna('unknown')

data_merged['asthma'] = data_merged['asthma'].map({
    '1.0': 'yes',
    '2.0': 'no',
    '3.0': 'refused',
    '9.0': 'unknown'
}).fillna('unknown')

data_merged['diabetes'] = data_merged['diabetes'].map({
    '1.0': 'yes',
    '2.0': 'no',
    '3.0': 'refused',
    '9.0': 'unknown'
}).fillna('unknown')

data_merged['education_adult'] = data_merged['education_adult'].map({
    '1.0': '<9th',
    '2.0': '9-11th',
    '3.0': 'GED Grad',
    '4.0': 'some College deg',
    '5.0': 'College or abv',
    '7.0': 'unknown',
    '9.0': 'unknown'
}).fillna('unknown')

data_merged['education_adolescent'] = data_merged['education_adolescent'].map({
    '1.0': '<9th',
    '2.0': '<9th',
    '3.0': '<9th',
    '4.0': '<9th',
    '5.0': '<9th',
    '6.0': '<9th',
    '7.0': '<9th',
    '8.0': '<9th',
    '9.0': '9-11th',
    '10.0': '9-11th',
    '11.0': '9-11th',
    '12.0': '9-11th',
    '13.0': 'HS Grad',
    '14.0': 'GED Grad',
    '15.0': 'some College deg',
    '55.0': '<5th',
    '66.0': '<9th',
    '77.0': 'unknown',
    '99.0': 'unknown'
}).fillna('unknown')

In [45]:
data_merged["year"] = 2017

In [46]:
from dotenv import dotenv_values

config = dotenv_values()

pg_user = config['POSTGRES_USER']
pg_host = config['POSTGRES_HOST']
pg_port = config['POSTGRES_PORT']
pg_db = config['POSTGRES_DB']
pg_schema = config['POSTGRES_SCHEMA']
pg_pass = config['POSTGRES_PASS']
url = f'postgresql://{pg_user}:{pg_pass}@{pg_host}:{pg_port}/{pg_db}'

In [47]:
engine = create_engine(url, echo=False)

In [48]:
engine.url

postgresql://soerenwenck:***@data-analytics-course-2.c8g8r1deus2v.eu-central-1.rds.amazonaws.com:5432/nf260325

In [49]:
with engine.begin() as conn: 
    result = conn.execute(text(f'SET search_path TO {pg_schema};'))

In [50]:
data_merged.to_sql('data_2017', engine, if_exists='replace',index=False)

306

In [51]:
# demo_2015 = pd.read_csv("../data/Database/NHANES2015-2016/demographics2015.csv")
# diet_2015 = pd.read_csv("../data/Database/NHANES2015-2016/dietary2015.csv")
# lab_2015 = pd.read_csv("../data/Database/NHANES2015-2016/laboratory2015.csv")
# exam_2015 = pd.read_csv("../data/Database/NHANES2015-2016/examination2015.csv")
# quest_2015 = pd.read_csv("../data/Database/NHANES2015-2016/questionnaire2015.csv")

# demo_2015.to_sql('demo_2015', engine, if_exists='replace',index=True)
# diet_2015.to_sql('diet_2015', engine, if_exists='replace',index=True)
# lab_2015.to_sql('lab_2015', engine, if_exists='replace',index=True)
# exam_2015.to_sql('exam_2015', engine, if_exists='replace',index=True)
# quest_2015.to_sql('quest_2015', engine, if_exists='replace',index=True)

In [52]:
# demo_2017 = pd.read_csv("../data/Database/NHANES2017-2018/demographics2017.csv")
# diet_2017 = pd.read_csv("../data/Database/NHANES2017-2018/dietary2017.csv")
# lab_2017 = pd.read_csv("../data/Database/NHANES2017-2018/laboratory2017.csv")
# exam_2017 = pd.read_csv("../data/Database/NHANES2017-2018/examination2017.csv")
# quest_2017 = pd.read_csv("../data/Database/NHANES2017-2018/questionnaire2017.csv")

# demo_2017.to_sql('demo_2017', engine, if_exists='replace',index=True)
# diet_2017.to_sql('diet_2017', engine, if_exists='replace',index=True)
# lab_2017.to_sql('lab_2017', engine, if_exists='replace',index=True)
# exam_2017.to_sql('exam_2017', engine, if_exists='replace',index=True)
# quest_2017.to_sql('quest_2017', engine, if_exists='replace',index=True)

In [53]:
# import pandas as pd
# from sqlalchemy import create_engine

# engine = create_engine(url, echo=False)

# # create dataframes from connection
# df1 = pd.read_sql("SELECT * FROM capstone_group_1.data_2013", engine)
# df2 = pd.read_sql("SELECT * FROM capstone_group_1.data_2015", engine)
# df3 = pd.read_sql("SELECT * FROM capstone_group_1.data_2017", engine)

# # concatenate
# combined_data = pd.concat([df1, df2, df3], ignore_index=True)
# combined_data.to_sql('capstone_group_1.combined_data', engine, if_exists='replace',index=True)

In [54]:
data_merged

,ID,gender,age,ethnicity,country_of_birth,us_citizen,education_adult,education_adolescent,household_size,no_of_kids_u6,...,overweight,cancer,smoker,alcoholic_drinks,trouble_sleeping,diabetes,cig_p_d,BP_med,hours_sleeping,year
0,93703,female,2,asian,USA,US-citizen,unknown,unknown,5,3,...,unknown,unknown,unknown,<NA>,nan,no,NaN,NaN,NaN,2017
1,93704,male,2,white,USA,US-citizen,unknown,unknown,4,2,...,unknown,unknown,unknown,<NA>,nan,no,NaN,NaN,NaN,2017
2,93705,female,66,black,USA,US-citizen,9-11th,unknown,1,0,...,no,no,not at all,1,2.0,no,NaN,1.0,8.0,2017
3,93706,male,18,asian,USA,US-citizen,unknown,some College deg,5,0,...,no,unknown,unknown,<NA>,2.0,no,NaN,NaN,10.5,2017
4,93707,male,13,others,USA,US-citizen,unknown,<9th,7,0,...,unknown,unknown,unknown,<NA>,nan,no,NaN,NaN,NaN,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8361,102952,female,70,asian,others,US-citizen,GED Grad,unknown,2,0,...,no,no,unknown,<NA>,2.0,refused,NaN,NaN,8.5,2017
8362,102953,male,42,mexican,others,US-citizen,GED Grad,unknown,1,0,...,yes,no,not at all,12,1.0,no,NaN,NaN,6.0,2017
8363,102954,female,41,black,USA,US-citizen,College or abv,unknown,7,3,...,yes,no,unknown,<NA>,2.0,no,NaN,NaN,8.0,2017
8364,102955,female,14,black,USA,US-citizen,unknown,<9th,4,0,...,unknown,unknown,unknown,<NA>,nan,no,NaN,NaN,NaN,2017
8365,102956,male,38,white,USA,US-citizen,some College deg,unknown,5,0,...,yes,no,every day,2,1.0,no,20.0,NaN,8.0,2017